### ISSUE TITLE
Game Over logika

### ISSUE THREAD

**Issue by Hangalik** [Hangalik/projektlabor#15]
Jelenleg nincs megvalósítva, hogy mikor van vége a játéknak és hogy akkor mi történik.

A Floor gameOver metódusa jó lehet, de inkább térjen vissza egy igaz/hamissal és a Controller hívja meg minden lépés után és a visszatérési értéktől függően megjeleníti a Result-okat.

**!!A Box amIPushable függvénye nincs megírva és az kritikus ehhez!!**

**Comment by remenyi** [comment]
Megírtam az amIPushable metódust. Átírtam a Floor gameOver metódusát, hogy bool értékkel térjenek vissza.

**Comment by Hangalik** [comment]
Messengeren leírtam a problémákat. Légyszíves javítsd!

Meg a Controllerbe is rakd bele a megfelelő részt, az is ehhez tartozik. Ehhez még annyi extra, hogy le kell tiltani onnantól a játékon a navigálást. Ez igazából annyi, hogy `gamePanel.getInputMap(IFW).clear()` amit a gameWindow-ban lehet. (Kell egy új metódus a gameWindow-ba, amit meghív a Controller 😃 )

**Comment by remenyi** [comment]
Átírtam a Box testMovability metódusát úgy. hogy ha csak dobozok vannak a tolt objektum előtt a d irányban egy fal elemig, akkor nem tolható (ha minkás lenne azt szétlapítaná). A Controllerbe beletettem a játék végét ellenőrző logikát, illetve a letiltást (ebben nem vagyok biztos, hogy jól csináltam).
